version: '3'

services:
  hhdb:
    image: hhdb:latest
    container_name: hadoop-hive-hbase
    ports:
     - "9864:9864"
     - "9870:9870"
     - "8088:8088"
     - "10000:10000"
     - "16010:16010"
     - "16030:16030"
     - "16020:16020"
    command: bash
    tty: true
    stdin_open: true
    build:
      context: .
    volumes: 
      - "/home"